**Synopsis**: [Isaac][Omniverse][2022.1.1] ISAAC SIM has incorrect importlib-metadata version on Windows using Anaconda

**Description**:

Following this issue: https://nvbugswb.nvidia.com/NvBugs5/SWBug.aspx?bugid=3837533 , the user will encounter another error when running `time_stepping.py`:

```
> set ISAAC_SIM="%LOCALAPPDATA%\ov\pkg\isaac_sim-2022.1.1"
> cd %ISAAC_SIM%
> conda activate isaac-sim
> call setup_conda_env.bat
> :: cd elsewhere
> python %ISAAC_SIM%\standalone_examples\api\omni.isaac.core\time_stepping.py
...
2022-10-18 17:48:13 [2,993ms] [Error] [omni.ext.impl._internal] Failed to import python module gym from c:\users\johnson\appdata\local\ov\pkg\isaac_sim-2022.1.1\exts\omni.isaac.ml_archive\pip_prebundle. Error: 'EntryPoints' object has no attribute 'get'. Traceback:
Traceback (most recent call last):
  File "C:\Users\Johnson\AppData\Local\ov\pkg\isaac_sim-2022.1.1/kit/plugins/bindings-python\omni\ext\impl\_internal.py", line 151, in _custom_importer
    return _import_public(ext_module.path, ext_module.name)
  File "C:\Users\Johnson\AppData\Local\ov\pkg\isaac_sim-2022.1.1/kit/plugins/bindings-python\omni\ext\impl\_internal.py", line 78, in _import_public
    module = import_module(module_name)
  File "C:\Users\Johnson\AppData\Local\ov\pkg\isaac_sim-2022.1.1/kit/plugins/bindings-python\omni\ext\impl\custom_importer.py", line 76, in import_module
    return importlib.import_module(name)
  File "C:\Users\Johnson\anaconda3\envs\isaac-sim\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 967, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "C:\Users\Johnson\anaconda3\envs\isaac-sim\lib\site-packages\gym\__init__.py", line 13, in <module>
    from gym.envs import make, spec, register
  File "C:\Users\Johnson\anaconda3\envs\isaac-sim\lib\site-packages\gym\envs\__init__.py", line 10, in <module>
    _load_env_plugins()
  File "C:\Users\Johnson\anaconda3\envs\isaac-sim\lib\site-packages\gym\envs\registration.py", line 250, in load_env_plugins
    for plugin in metadata.entry_points().get(entry_point, []):
AttributeError: 'EntryPoints' object has no attribute 'get'

2022-10-18 17:48:13 [2,997ms] [Error] [carb.scripting-python.plugin] Exception: Extension python module: 'gym' in 'c:\users\johnson\appdata\local\ov\pkg\isaac_sim-2022.1.1\exts\omni.isaac.ml_archive\pip_prebundle' failed to load.

At:
  C:\Users\Johnson\AppData\Local\ov\pkg\isaac_sim-2022.1.1/kit/plugins/bindings-python\omni\ext\impl\_internal.py(177): startup
  C:\Users\Johnson\AppData\Local\ov\pkg\isaac_sim-2022.1.1/kit/plugins/bindings-python\omni\ext\impl\_internal.py(268): startup_extension
  PythonExtension.cpp::startup()(2): <module>
  C:\Users\Johnson\AppData\Local\ov\pkg\isaac_sim-2022.1.1/exts/omni.isaac.kit\omni\isaac\kit\simulation_app.py(293): _start_app
  C:\Users\Johnson\AppData\Local\ov\pkg\isaac_sim-2022.1.1/exts/omni.isaac.kit\omni\isaac\kit\simulation_app.py(167): __init__
  C:\Users\Johnson\AppData\Local\ov\pkg\isaac_sim-2022.1.1\standalone_examples\api\omni.isaac.core\time_stepping.py(12): <module>

2022-10-18 17:48:13 [2,997ms] [Error] [omni.ext.plugin] [ext: omni.isaac.ml_archive-1.1.0] Failed to startup python extension.
...
```

We can inspect the versions of the `importlib-metadata` package:

```
> :: python.bat
> %ISAAC_SIM%\python.bat -m pip show importlib-metadata
Name: importlib-metadata
Version: 4.11.4
> :: conda
> pip show importlib-metadata
Name: importlib-metadata
Version: 5.0.0
```

This issue arises because the old version of the `gym` package uses a deprecated attribute of the `importlib-metadata` package.

The solution is to either downgrade the `importlib-metadata` package: https://stackoverflow.com/a/73932581 ;
or upgrade the `gym` package: https://github.com/openai/gym/issues/3110 .

The default python.bat does not encounter this issue due to the dependency files `$ISAAC_SIM/kit/PACKAGE-DEPS.yaml` and `$ISAAC_SIM/kit/DEPS.yaml`, which require `importlib-metadata` version 4.11.4 (instead of version 5.0.0 in the conda environment):

```
importlib-metadata:
  licenseFile: null
  packageName: importlib-metadata
  packageType: pip
  source:
    branch: null
    change: null
    path: null
    scm: null
  swipat: null
  version: 4.11.4
```

Therefore this issue can be fixed with:

```
> pip install importlib-metadata==4.11.4
```

```
> set ISAAC_SIM="%LOCALAPPDATA%\ov\pkg\isaac_sim-2022.1.1"
> cd %ISAAC_SIM%
> conda activate isaac-sim
> call setup_conda_env.bat
> :: cd elsewhere
> python %ISAAC_SIM%\standalone_examples\api\omni.isaac.core\time_stepping.py
> :: no more error messages
```

The true fix for this is to add an entry under `dependencies.pip` in `environment.yaml`:

```
- importlib-metadata==4.11.4
```

**Module**: Omniverse - Isaac Sim
